"""004_migration

Revision ID: 150614c962e3
Revises: 7acd5df6e8bf
Create Date: 2024-10-11 05:29:30.440333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '150614c962e3'
down_revision: Union[str, None] = '7acd5df6e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'driver_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('driver_class', postgresql.ENUM('econom', 'comfortable', 'business', name='driver_lassenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
