"""005_migration

Revision ID: 52aa5cc02f94
Revises: 150614c962e3
Create Date: 2024-10-11 05:30:20.921444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52aa5cc02f94'
down_revision: Union[str, None] = '150614c962e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('driver_class', sa.Enum('econom', 'comfortable', 'business', name='driverclassenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'driver_class')
    # ### end Alembic commands ###
