"""013_migration

Revision ID: 79b5a45bcbcf
Revises: ef6972e649fe
Create Date: 2024-10-14 07:58:32.095377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b5a45bcbcf'
down_revision: Union[str, None] = 'ef6972e649fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'messageDigest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('messageDigest', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
