"""Initial migration

Revision ID: 9be89c8902e4
Revises: 
Create Date: 2024-10-10 23:56:17.911955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be89c8902e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_building'), 'house', ['building'], unique=False)
    op.create_index(op.f('ix_house_id'), 'house', ['id'], unique=False)
    op.create_index(op.f('ix_house_number'), 'house', ['number'], unique=False)
    op.create_index(op.f('ix_house_street'), 'house', ['street'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_street'), table_name='house')
    op.drop_index(op.f('ix_house_number'), table_name='house')
    op.drop_index(op.f('ix_house_id'), table_name='house')
    op.drop_index(op.f('ix_house_building'), table_name='house')
    op.drop_table('house')
    # ### end Alembic commands ###
