"""001_migration

Revision ID: c32aca645a16
Revises: cfbddaf8dadb
Create Date: 2024-10-11 04:47:51.038830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32aca645a16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tel', sa.String(), nullable=False),
    sa.Column('car', sa.String(), nullable=False),
    sa.Column('driver_class', sa.Enum('econom', 'comfortable', 'business', name='driverclassenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_building'), 'house', ['building'], unique=False)
    op.create_index(op.f('ix_house_id'), 'house', ['id'], unique=False)
    op.create_index(op.f('ix_house_number'), 'house', ['number'], unique=False)
    op.create_index(op.f('ix_house_street'), 'house', ['street'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('house_from_id', sa.Integer(), nullable=False),
    sa.Column('house_from', sa.String(), nullable=False),
    sa.Column('house_to_id', sa.Integer(), nullable=False),
    sa.Column('house_to', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_driver_id'), 'order', ['driver_id'], unique=False)
    op.create_index(op.f('ix_order_house_from'), 'order', ['house_from'], unique=False)
    op.create_index(op.f('ix_order_house_from_id'), 'order', ['house_from_id'], unique=False)
    op.create_index(op.f('ix_order_house_to'), 'order', ['house_to'], unique=False)
    op.create_index(op.f('ix_order_house_to_id'), 'order', ['house_to_id'], unique=False)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_index(op.f('ix_order_order_date'), 'order', ['order_date'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_order_date'), table_name='order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_index(op.f('ix_order_house_to_id'), table_name='order')
    op.drop_index(op.f('ix_order_house_to'), table_name='order')
    op.drop_index(op.f('ix_order_house_from_id'), table_name='order')
    op.drop_index(op.f('ix_order_house_from'), table_name='order')
    op.drop_index(op.f('ix_order_driver_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_house_street'), table_name='house')
    op.drop_index(op.f('ix_house_number'), table_name='house')
    op.drop_index(op.f('ix_house_id'), table_name='house')
    op.drop_index(op.f('ix_house_building'), table_name='house')
    op.drop_table('house')
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
