"""014_migration

Revision ID: d1427aedabe4
Revises: 79b5a45bcbcf
Create Date: 2024-10-15 07:06:35.288787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1427aedabe4'
down_revision: Union[str, None] = '79b5a45bcbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('house_from_street', sa.String(), nullable=False))
    op.add_column('order', sa.Column('house_from_building', sa.String(), nullable=True))
    op.add_column('order', sa.Column('house_from_number', sa.String(), nullable=False))
    op.add_column('order', sa.Column('house_to_street', sa.String(), nullable=False))
    op.add_column('order', sa.Column('house_to_building', sa.String(), nullable=True))
    op.add_column('order', sa.Column('house_to_number', sa.String(), nullable=False))
    op.add_column('order', sa.Column('driver_class', sa.Enum('econom', 'comfortable', 'business', name='driverclassenum'), nullable=False))
    op.add_column('order', sa.Column('car', sa.String(), nullable=False))
    op.drop_index('ix_order_house_from', table_name='order')
    op.drop_index('ix_order_house_to', table_name='order')
    op.create_index(op.f('ix_order_car'), 'order', ['car'], unique=False)
    op.create_index(op.f('ix_order_driver_class'), 'order', ['driver_class'], unique=False)
    op.create_index(op.f('ix_order_house_from_building'), 'order', ['house_from_building'], unique=False)
    op.create_index(op.f('ix_order_house_from_number'), 'order', ['house_from_number'], unique=False)
    op.create_index(op.f('ix_order_house_from_street'), 'order', ['house_from_street'], unique=False)
    op.create_index(op.f('ix_order_house_to_building'), 'order', ['house_to_building'], unique=False)
    op.create_index(op.f('ix_order_house_to_number'), 'order', ['house_to_number'], unique=False)
    op.create_index(op.f('ix_order_house_to_street'), 'order', ['house_to_street'], unique=False)
    op.drop_column('order', 'house_to')
    op.drop_column('order', 'house_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('house_from', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('house_to', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_order_house_to_street'), table_name='order')
    op.drop_index(op.f('ix_order_house_to_number'), table_name='order')
    op.drop_index(op.f('ix_order_house_to_building'), table_name='order')
    op.drop_index(op.f('ix_order_house_from_street'), table_name='order')
    op.drop_index(op.f('ix_order_house_from_number'), table_name='order')
    op.drop_index(op.f('ix_order_house_from_building'), table_name='order')
    op.drop_index(op.f('ix_order_driver_class'), table_name='order')
    op.drop_index(op.f('ix_order_car'), table_name='order')
    op.create_index('ix_order_house_to', 'order', ['house_to'], unique=False)
    op.create_index('ix_order_house_from', 'order', ['house_from'], unique=False)
    op.drop_column('order', 'car')
    op.drop_column('order', 'driver_class')
    op.drop_column('order', 'house_to_number')
    op.drop_column('order', 'house_to_building')
    op.drop_column('order', 'house_to_street')
    op.drop_column('order', 'house_from_number')
    op.drop_column('order', 'house_from_building')
    op.drop_column('order', 'house_from_street')
    # ### end Alembic commands ###
