"""010_migration

Revision ID: e0753321a50e
Revises: a373e48f8611
Create Date: 2024-10-14 03:52:35.687552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0753321a50e'
down_revision: Union[str, None] = 'a373e48f8611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crl_id'), 'crl', ['id'], unique=False)
    op.create_index(op.f('ix_crl_token'), 'crl', ['token'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_crl_token'), table_name='crl')
    op.drop_index(op.f('ix_crl_id'), table_name='crl')
    op.drop_table('crl')
    # ### end Alembic commands ###
