"""012_migration

Revision ID: ef6972e649fe
Revises: ff2a2f86a40b
Create Date: 2024-10-14 07:46:58.655322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6972e649fe'
down_revision: Union[str, None] = 'ff2a2f86a40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('messageDigest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'messageDigest')
    # ### end Alembic commands ###
