"""011_migration

Revision ID: ff2a2f86a40b
Revises: e0753321a50e
Create Date: 2024-10-14 07:04:50.701101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2a2f86a40b'
down_revision: Union[str, None] = 'e0753321a50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_driver_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.create_foreign_key('order_driver_id_fkey', 'order', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###
